# LLM Deep Search Configuration (English)

# These aspects will be used to guide the search for company information
specific_aspects_for_report_guidance:
  - "precise founding year of the company (exact date if available)"
  - "detailed headquarters location including city, country, and address if available"
  - "full names of the founding team members and current CEO"
  - "detailed ownership structure (e.g., public company with stock symbol, private company with major investors, etc.)"
  - "last 2-3 years of annual revenue with exact figures and currency (specify fiscal year periods)"
  - "exact employee count (current or most recently reported) with source and date"
  - "all funding rounds with exact amounts, dates, and lead investors"
  - "detailed product portfolio with specific product names and core features, including year of launch if available"
  - "underlying technologies used by the company for their products/services"
  - "primary customer types (B2B, B2C, B2G) with specific industry focus"
  - "industries served or targeted by the company"
  - "geographic markets where the company operates or sells its products"
  - "major clients or case studies with specific names"
  - "strategic initiatives, partnerships, or mergers & acquisitions"
  - "key competitors mentioned within the company's industry"
  - "any pending mergers, acquisitions, or significant organizational changes"

llm_api_settings:
  model_name: "gpt-4o-mini-search-preview" # Ensure this is the model you want
  system_prompt: "You are an AI Business Analyst. Your task is to generate a detailed, structured, and factual business report on a given company. Utilize your web search capabilities to find the most current information. When financial data is requested, if multiple recent years are found, include data for each distinct year, clearly stating the period. Prioritize the most recent full fiscal year data. The report MUST follow the exact sections in the prompt, as these will be used to extract structured data into a JSON schema. Be concise and data-driven. Do not include conversational intros, outros, or disclaimers. For sections where you cannot find information, simply include a brief note like 'No specific data found on [topic]' rather than leaving the section empty."
  # max_tokens: 4000
  # temperature: 0.0

# Main user prompt template structured to match our JSON schema
user_prompt_template: |
  Please generate a detailed Business Analytics Report for the company: '{company_name_placeholder}'.

  Your primary goal is to extract and present factual data that will later be structured according to a specific JSON schema. 
  When reporting financial figures (like revenue, ARR, funding), prioritize data for the most recent fiscal year. If multiple years of data are found, include all such figures, clearly stating the period/year each figure refers to.

  The report MUST follow this structure that corresponds to our JSON schema:

  1. **Basic Company Information:**
     * Company Name: Official legal name of the company.
     * Founding Year: Exact year when the company was founded.
     * Headquarters Location: City and country of the company's headquarters.
     * Founders: Names of all company founders.
     * Ownership Background: Information about ownership structure (public/private, parent companies, etc.)

  2. **Products and Technology:**
     * Core Products & Services: List each major product/service with its launch year (if available).
     * Underlying Technologies: Key technologies, frameworks, or platforms used by the company.

  3. **Market and Customer Information:**
     * Customer Types: Primary customer categories (B2B, B2C, B2G).
     * Industries Served: Specific industries or sectors the company targets.
     * Geographic Markets: Countries or regions where the company operates.

  4. **Financial and HR Details:**
     * Revenue History: For each reported year, provide the amount, currency, and type (total revenue, ARR, etc.).
     * Funding Rounds: For each round, include the round name, year closed, amount, currency, and key investors.
     * Employee Count: Current or most recent employee count with the reporting year.

  5. **Strategic Information:**
     * Major Clients or Case Studies: Notable customers or implementation examples.
     * Strategic Initiatives: Key partnerships, expansions, or strategic moves.
     * Key Competitors: Main competitors in their space.
     * Overall Summary: Brief summary of the company's position and outlook.

  {additional_aspects_placeholder}

  Provide a concise, data-driven report. Avoid conversational filler, disclaimers, or speculative statements. All factual data, especially figures like revenue, subscriber counts, and pricing, should be cited with sources, either inline or in a concluding 'Sources' list. Respond only in English.