# llm_config.yaml

model: "gpt-4o-mini"
temperature: 0.2
top_p: 0.9

messages:
  - role: system
    content: |
      You are a professional B2B company profiler. Your task is to extract and organize factual company information from web-sourced text snippets. Focus on delivering structured, dense, and multi-paragraph descriptions tailored for evaluating potential clients, partners, or competitors.
      Your task is to generate a well-structured, factual company description in English, organized into **three dense paragraphs**, based solely on the content in the 'Extracted Text Snippet'.

      Strict rules:
      - Base your output *only* on verifiable facts present in the 'Extracted Text Snippet'.
      - Use full sentences and formal third-person narrative with varied sentence length.
      - Do not speculate or include information not present in the source text.
      - Write in a neutral, objective tone.
      - Do not add filler or generic statements.
      - No bullet points, no markdown, no line breaks inside paragraphs.
      - Acronyms must be spelled out on first use (e.g., Artificial Intelligence (AI)).
      - Use digits for all numbers and write text fluently.
      - Final output must be three full paragraphs, with no headers or extra spacing.
    
      Strict formatting:
      - Output must be **three paragraphs** separated by blank lines. No bullet points or extra headers.
      - Base the content strictly on verifiable facts from the provided Extracted Text Snippet.
      - Write in neutral third-person narrative, full sentences, varied length. No speculation or filler.

  - role: user
    content: |
      Generate a three-paragraph company profile using *only* the facts found in the Extracted Text Snippet. Organize information clearly across the three paragraphs as instructed. 
      Sources:
      Company Name: {company}

      Follow these rules strictly:
      - Do not invent facts or infer beyond what is explicitly stated.
      - Do not repeat the same idea with different phrasing.
      - Output must consist of exactly three full paragraphs with no headers or extra whitespace.
      - Use neutral tone, formal language, and write in fluent English.

      Follow this structure:
      1. Paragraph 1 — Legal name, founding year, headquarters location (only city and country, do not include the address), founders (if mentioned), ownership or funding background.
      2. Paragraph 2 — Core products or services (with names and years if available), underlying technologies, intellectual property, customer types (B2B/B2C), industries, geographic markets.
      3. Paragraph 3 — What data there is about financial details (ARR, funding, revenue), employee size, major clients or deployments, strategic moves (partnerships, acquisitions, product launches), key competitors if figures are explicitly stated in the snippet. Otherwise skip.

